services:
  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8082:8082"
    volumes:
      - ./trino-config/config.properties:/etc/trino/config.properties:ro
      - ./trino-config/jvm.config:/etc/trino/jvm.config:ro
      - ./trino-config/log.properties:/etc/trino/log.properties:ro
      - ./trino-config/node.properties:/etc/trino/node.properties:ro
      - ./trino-config/catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro
      # - ./trino-data:/etc/trino/catalog
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - WAREHOUSE_DIR=${WAREHOUSE_DIR}
      - CATALOG_MANAGEMENT=dynamic
    depends_on:
      - nessie

  nessie:
    image: ghcr.io/projectnessie/nessie
    ports:
      - "19120:19120"
