services:
  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8082:8082"
    volumes:
      - ./trino-config:/etc/trino
      - ./trino-data:/data/trino
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - WAREHOUSE_DIR=${WAREHOUSE_DIR}
    depends_on:
      - nessie

  nessie:
    image: ghcr.io/projectnessie/nessie
    ports:
      - "19120:19120"
